[package]
name = "qir-backend"
version = "0.3.0"
authors = ["Microsoft"]
edition = "2021"
license = "MIT"

[dependencies]
qir-stdlib = { path = "../stdlib" }
rand = "0.8.5"
rustc-hash = "1.1.0"
num-complex = "0.4"
num-traits = "0.2.14"
num-bigint = { version = "0.4.3", default-features = false }
ndarray = "0.15.4"
bitvec = "1.0.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "gates"
harness = false

[[bench]]
name = "grover"
harness = false

[lib]
crate-type = ["staticlib","rlib"]
bench = false
