# -Ccontrol-flow-guard: Enable Control Flow Guard (https://learn.microsoft.com/en-us/windows/win32/secbp/control-flow-guard).
# -Ctarget-feature=+crt-static: Statically link the CRT (required to link the spectre-mitigated CRT).
# -Clink-args=/DYNAMICBASE /CETCOMPAT: Enable "shadow stack" (https://docs.microsoft.com/en-us/cpp/build/reference/cetcompat)
[target.'cfg(target_os = "windows")']
rustflags = ["-Ccontrol-flow-guard", "-Ctarget-feature=+crt-static", "-Clink-args=/DYNAMICBASE /CETCOMPAT"]
