[package]
name = "qir-runner"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
branch = "master"
default-features = false
features = []

[dependencies.qir-backend]
path = "../backend"

[features]
default = []
llvm11-0 = ["inkwell/llvm11-0"]
llvm12-0 = ["inkwell/llvm12-0"]
llvm13-0 = ["inkwell/llvm13-0"]
llvm14-0 = ["inkwell/llvm14-0"]
