[package]
name = "qir-runner"
version = "0.6.0"
edition = "2021"
license = "MIT"

[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
branch = "master"
default-features = false
features = ["llvm14-0"]

[dependencies]
qir-stdlib = { path = "../stdlib", features = ["range-support"] }
qir-backend = { path = "../backend" }
clap = { version = "4.5.3", features = [ "cargo" ] }
msvc_spectre_libs = { version = "0.1", features = ["error"] }

