name: qirrunner-governance-$(BuildId)

trigger:
- main

pr:
- main

schedules:
- cron: "0 9 * * Sat"
  displayName: 'Build for CodeQL'
  branches:
    include:
    - main
  always: true

variables:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "1.78"
  AUDITWHEEL_TAG: "manylinux_2_31_x86_64"
  PYTHON_VERSION: "3.11"

# This pipeline builds the manylinux wheels for the qirrunner package
# as that target uses all of the dependencies

jobs:
- job: "qirrunner_governance"
  pool:
    vmImage: 'ubuntu-20.04'
  timeoutInMinutes: 240
  steps:
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component detection'

  - task: RustInstaller@1
    inputs:
      rustVersion: ms-$(RUST_TOOLCHAIN_VERSION)
      cratesIoFeedOverride: $(cratesIoFeedOverride)
      toolchainFeed: $(toolchainFeed)
    displayName: Install Rust toolchain

  - script: |
      rustc --version
      rustc --print target-list
    displayName: View rust target info

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)

  - task: CodeQL3000Init@0
    displayName: CodeQL Initialize

  - template: llvm.yml
    parameters:
      version: "14"
      os: "ubuntu-20.04"
      arch: "x86_64"
      directory: $(Build.SourcesDirectory)/target/llvm14-0
      arch_flags: ""

  - script: |
      cargo build -vv --release
    displayName: Build

  - script: |
      cargo test -vv --release -- --nocapture
    displayName: Test

  - script: |
      python -m pip install -U pip
      python -m pip install -r pip/requirements.txt
      python -m pip install -r pip/requirements-manylinux.txt
      python -m build --verbose --wheel --outdir target/raw-wheels ./pip
      python -m build --verbose --sdist --outdir target/wheels ./pip
      auditwheel repair --plat $(AUDITWHEEL_TAG) --wheel-dir target/wheels target/raw-wheels/*.whl
    displayName: Build Python packages

  - script: |
      python -m pip install -r pip/requirements-test.txt
      python -m pip install --force-reinstall --no-index --find-links=target/wheels qirrunner
      python -m pytest --verbose pip
    displayName: Test Python packages

  - task: CodeQL3000Finalize@0
    displayName: CodeQL Finalize
